version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - $HOME/dev/jenkins_home:/var/jenkins_home
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "8080:8080"
      - "50000:50000"

